name: build
on: push
jobs:
  matrix_builder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - id: set-matrix
      run: |
        npm ci
        echo $(pwd)
        ls
        mkdir tests/logs
        node scripts/e2e/split_tests.js
        content=`cat ./test_matrix.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=matrix::$content"
    - name: Archive Results
      uses: actions/upload-artifact@v2
      with:
        name: Results Artifact ${{ matrix.node-version }} with control flow
        path: ./test_matrix.json
  test_runner:
    name: Tests for Node ${{ matrix.node }} Specs ${{ matrix.specs }}
    needs: matrix_builder
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.node }} && echo ${{ matrix.specs }}