name: Build cht-core and test against node versions

on: [push, pull_request]

env:
  COUCH_URL: http://admin:pass@localhost:5984/medic-test
  COUCH_NODE_NAME: nonode@nohost
  BUILDS_SERVER: _couch/builds_testing
  STAGING_SERVER: _couch/builds
  TRAVIS_BUILD_NUMBER: $GITHUB_RUN_ID
  TRAVIS_BRANCH: $GITHUB_REF#refs/heads/


jobs:
  build:
    name: Compile the app 
    runs-on: ubuntu-16.04
  
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Set UPLOARD_URL var
      run: |
        if [[ -z "$UPLOAD_URL" ]]; then
          echo "UPLOAD_URL=https://staging.dev.medicmobile.org" >> $GITHUB_ENV
          echo "BUILDS_SERVER=_couch/builds_external" >> $GITHUB_ENV
        fi
    - name: Get branch name
      uses: nelonoel/branch-name@v1.0.1
        echo "TRAVIS_BUILD_NUMBER=$GITHUB_RUN_ID" >> $GITHUB_ENV
        echo "TRAVIS_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Couch Start
      run: ./scripts/travis/couch-start
    - name: xsltprox install
      run: sudo apt-get install xsltproc
    - name: Create logs directory
      run: mkdir tests/logs
    - name: npm CI
      run: npm ci
    - name: Grunt Install
      run: npm install -g grunt-cli
    - name: Horti Install
      run: npm install -g horticulturalist
    - name: Configure Couch
      run: ./scripts/travis/couch-config
    - name: Grunt CI-Compile
      run: |
        node --stack_size=10000 `which grunt` ci-compile
    - name: Publish
      run: |
        node --stack_size=10000 `which grunt` publish-for-testing
        cd scripts/travis
        npm install
        node ./publish.js
        
  
  test-e2e:
    needs: build
    name: e2e Tests for Node version ${{ matrix.node-version }}
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Couch Start
      run: ./scripts/travis/couch-start
    - name: xsltprox install
      run: sudo apt-get install xsltproc
    - name: Create logs directory
      run: mkdir tests/logs
    - name: npm CI
      run: npm ci
    - name: Grunt Install
      run: npm install -g grunt-cli
    - name: Horti Install
      run: npm install -g horticulturalist
    - name: Configure Couch
      run: ./scripts/travis/couch-config
    - name: Echo Vars
      run: |
        echo "HORTI_BUILDS_SERVER=${UPLOAD_URL}/${BUILDS_SERVER}"
        echo "--install=medic:medic:test-${TRAVIS_BUILD_NUMBER}"
        echo "COUCH_URL=${COUCH_URL}"
    - name: Curl Couch_url
      run: curl ${COUCH_URL}
    - name: horti setup
      run: |    
        echo "COUCH_URL=$COUCH_URL HORTI_BUILDS_SERVER=$UPLOAD_URL/$BUILDS_SERVER"
        COUCH_URL=$COUCH_URL HORTI_BUILDS_SERVER=$UPLOAD_URL/$BUILDS_SERVER horti --local --install=medic:medic:test-$TRAVIS_BUILD_NUMBER > tests/logs/horti.log &
    - name: Test it!
      run: node --stack_size=10000 `which grunt` ci-e2e
