name: Build cht-core and test against node versions

on: [push, pull_request]

env:
  COUCH_URL: http://admin:pass@localhost:5984/medic-test
  COUCH_NODE_NAME: nonode@nohost
  BUILDS_SERVER: _couch/builds_testing
  STAGING_SERVER: _couch/builds
  MARKET_URL: ${{ secrets.MARKET_URL }}


jobs:
  build:
    name: Compile the app 
    runs-on: ubuntu-18.04

    steps:
    - name: Get Docker Hub username
      id: get-docker-hub-username
      run: echo '::set-output name=dockerhub_username::${{ secrets.DOCKERHUB_USERNAME }}'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: steps.get-docker-hub-username.outputs.dockerhub_username
    - name: Set MARKET_URL var
      run: |
        if [[ -z "$MARKET_URL" ]]; then
          echo "MARKET_URL=https://staging.dev.medicmobile.org" >> $GITHUB_ENV
          echo "BUILDS_SERVER=_couch/builds_external" >> $GITHUB_ENV
          echo "STAGING_SERVER=_couch/builds_external" >> $GITHUB_ENV
        fi
    - name: Get branch name
      uses: nelonoel/branch-name@1ea5c86cb559a8c4e623da7f188496208232e49f
    - name: Set Travis Vars
      run: |
        echo "TRAVIS_BUILD_NUMBER=$GITHUB_RUN_ID" >> $GITHUB_ENV
        echo "TRAVIS_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Couch Start
      run: ./scripts/travis/couch-start
    - name: Create logs directory
      run: mkdir tests/logs
    - name: npm CI
      run: npm ci
    - name: Grunt Install
      run: npm install -g grunt-cli
    - name: Configure Couch
      run: ./scripts/travis/couch-config
    - name: Grunt CI-Compile
      run: |
        node --stack_size=10000 `which grunt` ci-compile-github
    - name: Publish for testing
      run: |
        node --stack_size=10000 `which grunt` publish-for-testing
    - name: Publish
      run: |
        cd scripts/travis
        npm install
        node ./publish.js
      if: ${{ github.event_name != 'pull_request' }}
  

  matrix_builder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkem out
      uses: actions/checkout@v2
    - id: set-matrix
    - name : Generate test_matrix.json
      run: |
        npm ci
        echo $(pwd)
        ls
        mkdir tests/logs
        node scripts/e2e/split_tests.js
        content=`cat ./test_matrix.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=matrix::$content"
    - name: Archive Results
      uses: actions/upload-artifact@v2
      with:
        name: Test Matrix
        path: ./test_matrix.json

  default-config-tests:
    needs: build
    name: Default Config Test
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Grunt Install
      run: npm install -g grunt-cli
    - name: NPM 
      run: npm ci
    - name: Run Tests
      run: node --stack_size=10000 `which grunt` exec:test-config-default

  standard-config-tests:
    needs: build
    name: Standard Config Testst
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Grunt Install
      run: npm install -g grunt-cli
    - name: NPM 
      run: npm ci
    - name: Run Tests
      run: node --stack_size=10000 `which grunt` exec:test-config-standard

  test-e2e:
    needs: [build, matrix_builder]
    name: e2e Tests for Node version ${{ matrix.node }}
    runs-on: ubuntu-18.04

    strategy:
      matrix: ${{fromJSON(needs.matrix_builder.outputs.matrix)}}

    steps:
    - name: Get Docker Hub username
      id: get-docker-hub-username
      run: echo '::set-output name=dockerhub_username::${{ secrets.DOCKERHUB_USERNAME }}'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: steps.get-docker-hub-username.outputs.dockerhub_username
    - name: Set Travis Vars
      run: |
        echo "TRAVIS_BUILD_NUMBER=$GITHUB_RUN_ID" >> $GITHUB_ENV
        echo "TEST_SUITE=integration" >> $GITHUB_ENV
    - name: Set UPLOARD_URL var
      run: |
        if [[ -z "$MARKET_URL" ]]; then
          echo "MARKET_URL=https://staging.dev.medicmobile.org" >> $GITHUB_ENV
          echo "BUILDS_SERVER=_couch/builds_external" >> $GITHUB_ENV
          echo "STAGING_SERVER=_couch/builds_external" >> $GITHUB_ENV
        fi
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Couch Start
      run: ./scripts/travis/couch-start
    - name: xsltprox install
      run: sudo apt-get install xsltproc
    - name: Create logs directory
      run: mkdir tests/logs
    - name: npm CI
      run: npm ci
    - name: Grunt Install
      run: npm install -g grunt-cli
    - name: Horti Install
      run: npm install -g horticulturalist
    - name: Configure Couch
      run: ./scripts/travis/couch-config
    - name: Echo Vars
      run: |
        echo "HORTI_BUILDS_SERVER=${MARKET_URL}/${BUILDS_SERVER}"
        echo "--install=medic:medic:test-${TRAVIS_BUILD_NUMBER}"
        echo "COUCH_URL=${COUCH_URL}"
    - name: Curl Couch_url
      run: curl ${COUCH_URL}
    - name: horti setup
      run: |    
        echo "COUCH_URL=$COUCH_URL HORTI_BUILDS_SERVER=$MARKET_URL/$BUILDS_SERVER"
        COUCH_URL=$COUCH_URL HORTI_BUILDS_SERVER=$MARKET_URL/$BUILDS_SERVER horti --local --install=medic:medic:test-$TRAVIS_BUILD_NUMBER > tests/logs/horti.log &
    - name: Test it!
      run: node --stack_size=10000 `which grunt` ci-e2e --specs=${{ matrix.specs }}
    - name: Dump Couch logs
      run: docker logs couch > tests/logs/couch.log 2>&1
      if: ${{ always() }}
    - name: Archive Results
      uses: actions/upload-artifact@v2
      with:
        name: Results Artifact ${{ matrix.node-version }} with control flow
        path: |
          tests/results
          tests/logs
      if: ${{ failure() }}
      