name: Build cht-core and test against node versions

on: [push, pull_request]

env:
  COUCH_URL: http://admin:pass@localhost:5984/medic-test
  COUCH_NODE_NAME: nonode@nohost
  BUILDS_SERVER: _couch/builds_testing
  STAGING_SERVER: _couch/builds

jobs:
  build:
    name: Compile the app 
    runs-on: ubuntu-18.04
  
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Couch Start
      run: ./scripts/travis/couch-start
    - name: xsltprox install
      run: sudo apt-get install xsltproc
    - name: build and test
      run: |
        mkdir tests/logs
        npm ci
        npm install -g grunt-cli
        npm install -g horticulturalist
        ./scripts/travis/couch-config
        echo "HORTI_BUILDS_SERVER=${UPLOAD_URL}/${BUILDS_SERVER}"
        echo "--install=medic:medic:test-${TRAVIS_BUILD_NUMBER}"
        echo "COUCH_URL=${COUCH_URL}"
        curl ${COUCH_URL}
        echo "COUCH_URL=$COUCH_URL HORTI_BUILDS_SERVER=$UPLOAD_URL/$BUILDS_SERVER"
        COUCH_URL=$COUCH_URL HORTI_BUILDS_SERVER=$UPLOAD_URL/$BUILDS_SERVER horti --local --install=medic:medic:test-$TRAVIS_BUILD_NUMBER > tests/logs/horti.log
        node --stack_size=10000 `which grunt` ci-compile
    - name: Publish
      run: |
        node --stack_size=10000 `which grunt` publish-for-testing
        cd scripts/travis
        npm install
        node ./publish.js
        
  
  # test:
  #   name: test for Node version ${{ matrix.node-version }}
  #   runs-on: ubuntu-18.04

  #   strategy:
  #     matrix:
  #       node-version: [8.x, 10.x, 12.x]

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: Setting up python 2.X
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '2.x' 
  #       architecture: 'x64' 
  #   - name: Installing wheel package for pip # This makes the warning about legacy installing go away. 
  #     uses: BSFishy/pip-action@v1
  #     with:
  #       packages: wheel
  #   - name: Installing pyxform # Install pyxform dependency. 
  #     uses: BSFishy/pip-action@v1
  #     with:
  #       packages: git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
  #   - name: npm ci and test
  #     run: npm ci && npm test